--- #YAML:1.0
name:               List-Vectorize
version:            0.12
abstract:           Functions for vectorized calculation
author:
    - Zuguang Gu <jokergoo@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:          
    Data::Dumper:  
    Test::More:    
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
